// mustakuusi-preact/src/components/Games/GameCard.tsx
import {Link} from "preact-router";
import {useEffect, useState} from "preact/hooks";
import {useInView} from "../../hooks/useInView";
import styles from "./GameCard.module.css";
import {getImageUrl} from "../../utils";

interface GameProps {
    title: string;
    imageSrc: string;
    date: string;
    description: string;
    categories: string[];
    detail: string;
    downloadLink: string;
    playLink: string;
}

interface GameCardProps {
    game: GameProps;
}

export const GameCard = ({
                             game: {
                                 title,
                                 imageSrc,
                                 date,
                                 categories,
                                 detail,
                                 downloadLink,
                                 playLink
                             }
                         }: GameCardProps) => {
    const {ref, isVisible} = useInView(0.18);
    const [countdown, setCountdown] = useState("");

    useEffect(() => {
        if (date) {
            const updateCountdown = () => {
                const now = new Date().getTime();
                const release = new Date(date).getTime();
                const diff = release - now;

                if (diff <= 0) {
                    setCountdown("");
                    return;
                }

                const days = Math.floor(diff / (1000 * 60 * 60 * 24));
                setCountdown(`${days} hari lagi`);
            };

            updateCountdown();
            const timer = setInterval(updateCountdown, 1000 * 60 * 60);

            return () => clearInterval(timer);
        }
    }, [downloadLink, date]);

    return (
        <div ref={ref}
             className={`${styles.container} ${styles.fadeUp} ${isVisible ? styles.visible : ""}`}>
            <div className={styles.card}>
                <img src={getImageUrl(imageSrc)} alt={`Image of ${title}`} className={styles.image}/>
                <h3 className={styles.title}>
                    <Link
                        href={`/m${detail}`}
                        onClick={() => {
                            const html = document.documentElement;
                            html.style.scrollBehavior = "auto";

                            requestAnimationFrame(() => {
                                window.scrollTo(0, 0);
                                requestAnimationFrame(() => {
                                    html.style.scrollBehavior = "smooth";
                                });
                            });
                        }}
                    >{title}</Link>
                </h3>
                <time class={styles.date} dateTime={date}>Dirilis: {new Date(date).toLocaleDateString("id-ID", {
                    year: 'numeric',
                    month: 'short',
                    day: '2-digit',
                    hour: 'numeric',
                    minute: 'numeric',
                })} WIB</time>
                <ul className={styles.categories}>
                    {
                        categories.map((category, id) => {
                            return <li key={id} className={styles.category}>{category}</li>;
                        })
                    }
                </ul>
                <div className={styles.links}>
                    {countdown && (
                        <h2 className={styles.badge}>{countdown}</h2>
                    )}
                    {!countdown && downloadLink && (
                        <a href={downloadLink} target="_blank" rel="noopener"><img
                            src={getImageUrl("googlebadge.png")}
                            alt="Unduh di Google Play"
                            className={styles.badge}
                        /></a>)}
                    {!countdown && playLink && (
                        <a href={playLink} target="_blank" rel="noopener"><img
                            src={getImageUrl("itchbadge.png")}
                            alt="Main di itch.io"
                            className={styles.badge}
                        /></a>)}
                </div>
            </div>
        </div>
    )
}

// mustakuusi-svelte/src/components/Games/GameCard.svelte
<script lang="ts">
    import {onDestroy, onMount} from "svelte";
    import styles from "./GameCard.module.css";
    import {useInView} from "../../hooks/useInView";
    import {getImageUrl} from "../../utils";

    interface GameProps {
        title: string;
        imageSrc: string;
        date: string;
        description: string;
        categories: string[];
        detail: string;
        downloadLink: string;
        playLink: string;
    }

    export let game: GameProps;

    const {inView, isVisible} = useInView(0.18);
    let countdown: string = "";

    let timer: number;

    const updateCountdown = () => {
        if (!game.date) return;

        const now = new Date().getTime();
        const release = new Date(game.date).getTime();
        const diff = release - now;

        if (diff <= 0) {
            countdown = "";
            clearInterval(timer);
            return;
        }

        const days = Math.floor(diff / (1000 * 60 * 60 * 24));
        countdown = `${days} hari lagi`;
    };

    onMount(() => {
        if (game.date) {
            updateCountdown();
            timer = setInterval(updateCountdown, 1000 * 60 * 60);
        }
    });

    onDestroy(() => {
        clearInterval(timer);
    });
</script>

<div
        use:inView
        class={`${styles.container} ${styles.fadeUp} ${$isVisible ? styles.visible : ""}`}
>
    <div class={styles.card}>
        <img
                src={getImageUrl(game.imageSrc)}
                alt={`Image of ${game.title}`}
                class={styles.image}
        />

        <h3 class={styles.title}>
            <a
                    href={`/y${game.detail}`}
                    on:click={() => {
                        const html = document.documentElement;
                        html.style.scrollBehavior = "auto";
                        requestAnimationFrame(() => {
                            window.scrollTo(0, 0);
                            requestAnimationFrame(() => {
                                html.style.scrollBehavior = "smooth";
                            });
                        });
                    }}
            >{game.title}</a>
        </h3>
        <time class={styles.date} dateTime={game.date}>Dirilis: {new Date(game.date).toLocaleDateString("id-ID", {
            year: 'numeric',
            month: 'short',
            day: '2-digit',
            hour: 'numeric',
            minute: 'numeric',
        })} WIB</time>

        <ul class={styles.categories}>
            {#each game.categories as category, id (id)}
                <li class={styles.category}>{category}</li>
            {/each}
        </ul>

        <div class={styles.links}>
            {#if countdown}
                <h2 class={styles.badge}>{countdown}</h2>
            {/if}
            {#if !countdown && game.downloadLink}
                <a href={game.downloadLink} target="_blank" rel="noopener"><img
                        src={getImageUrl("googlebadge.png")}
                        alt="Unduh di Google Play"
                        class={styles.badge}
                /></a>
            {/if}
            {#if !countdown && game.playLink}
                <a href={game.playLink} target="_blank" rel="noopener"><img
                        src={getImageUrl("itchbadge.png")}
                        alt="Main di itch.io"
                        class={styles.badge}
                /></a>
            {/if}
        </div>
    </div>
</div>
