// mustakuusi-angular/src/app/components/navbar/navbar.ts
import { Component, ElementRef, HostListener, OnInit } from '@angular/core';
import {NavigationEnd, Router, RouterLink} from '@angular/router';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule, RouterLink],
  templateUrl: './navbar.html',
  styleUrl: './navbar.css',
})
export class Navbar implements OnInit {
  menuOpen = false;
  currentPath = '';

  isHomePage = false;
  isGamePage = false;
  isCharacterPage = false;

  constructor(private router: Router, private elRef: ElementRef) {}

  ngOnInit(): void {
    const baseHref = document.querySelector('base')?.getAttribute('href') || '/';
    let path = this.router.url.replace(baseHref, '/').split('#')[0];
    this.currentPath = path;

    this.isHomePage = path === '/';
    this.isCharacterPage = path.startsWith('/character');
    this.isGamePage =
      !this.isHomePage &&
      !this.isCharacterPage &&
      !path.includes('privacy-policy');

    this.router.events.subscribe(event => {
      if (event instanceof NavigationEnd) {
        path = event.urlAfterRedirects.replace(baseHref, '/').split('#')[0];
        this.currentPath = path;
        this.isHomePage = path === '/';
        this.isCharacterPage = path.startsWith('/character');
        this.isGamePage =
          !this.isHomePage &&
          !this.isCharacterPage &&
          !path.includes('privacy-policy');
      }
    });
  }

  toggleMenu() {
    this.menuOpen = !this.menuOpen;
  }

  @HostListener('document:mousedown', ['$event'])
  @HostListener('document:touchstart', ['$event'])
  handleClickOutside(event: Event) {
    if (this.menuOpen && !this.elRef.nativeElement.contains(event.target)) {
      this.menuOpen = false;
    }
  }

  removeHash() {
    setTimeout(() => {
      history.replaceState(null, '', window.location.pathname);
    }, 200);
  }
}

// mustakuusi-preact/src/components/Navbar/Navbar.tsx
import {useEffect, useRef, useState} from "preact/hooks";
import {Link} from "preact-router";
import {useLocation} from "preact-iso";
import styles from "./Navbar.module.css";

export const Navbar = () => {
    const [menuOpen, setMenuOpen] = useState(false);
    const navbarRef = useRef<HTMLElement>(null);

    const location = useLocation();

    const BASE_PATH = "/m";
    const path = location.path.startsWith(BASE_PATH)
        ? location.path.slice(BASE_PATH.length) || "/"
        : location.path;

    const isHomePage = path === "/";
    const isGamePage = path !== "/" && !path?.includes("privacy-policy") && !path?.includes("character");
    const isCharacterPage = path?.startsWith("/character");

    useEffect(() => {
        const handleClickOutside = (event: Event) => {
            if (menuOpen && navbarRef.current && !navbarRef.current.contains(event.target as Node)) {
                setMenuOpen(false);
            }
        };

        document.addEventListener("mousedown", handleClickOutside);
        document.addEventListener("touchstart", handleClickOutside);
        return () => {
            document.removeEventListener("mousedown", handleClickOutside);
            document.addEventListener("touchstart", handleClickOutside);
        };
    }, [menuOpen]);

    return (
        <nav className={styles.navbar} ref={navbarRef}>
            <Link
                href="/m"
                className={styles.title}
                onClick={() => {
                    const html = document.documentElement;

                    html.style.scrollBehavior = "auto";
                    window.scrollTo(0, 0);

                    setTimeout(() => {
                        html.style.scrollBehavior = "smooth";
                    }, 50);
                }}
            >mustakuusi</Link>
            <div className={styles.menu}>
                <div
                    className={`${styles.burger} ${menuOpen ? styles.open : ""}`}
                    onClick={() => setMenuOpen(!menuOpen)}
                >
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
                <ul className={`${styles.menuItems} ${menuOpen && styles.menuOpen}`} onClick={() => setMenuOpen(false)}>
                    {(isHomePage || isGamePage) && (
                        <li>
                            <a href="#about" onClick={() => {
                                setTimeout(() => {
                                    history.replaceState(null, '', window.location.pathname);
                                }, 200);
                            }}>Tentang</a>
                        </li>
                    )}
                    {(isHomePage || isCharacterPage) && (
                        <li>
                            <a href="#games" onClick={() => {
                                setTimeout(() => {
                                    history.replaceState(null, '', window.location.pathname);
                                }, 200);
                            }}>Gim</a>
                        </li>
                    )}
                    {(isHomePage || isGamePage) && (
                        <li>
                            <a href="#characters" onClick={() => {
                                setTimeout(() => {
                                    history.replaceState(null, '', window.location.pathname);
                                }, 200);
                            }}>Karakter</a>
                        </li>
                    )}
                    {isGamePage && (
                        <li>
                            <a href="#screenshots" onClick={() => {
                                setTimeout(() => {
                                    history.replaceState(null, '', window.location.pathname);
                                }, 200);
                            }}>Cuplikan</a>
                        </li>
                    )}
                    <li>
                        <a href="#contact" onClick={() => {
                            setTimeout(() => {
                                history.replaceState(null, '', window.location.pathname);
                            }, 200);
                        }}>Kontak</a>
                    </li>
                </ul>
            </div>
        </nav>
    )
}
