// mustakuusi-react/src/pages/GamePage.tsx
import {useParams} from "react-router-dom";
import {useEffect} from "react";
import {Navbar} from "../components/Navbar/Navbar";
import {Hero} from "../components/Hero/Hero";
import {About} from "../components/About/About";
import {Characters} from "../components/Characters/Characters";
import {Screenshots} from "../components/Screenshots/Screenshots";
import {Contact} from "../components/Contact/Contact";
import characters from "../../../public/data/characters.json";
import games from "../../../public/data/games.json";

interface CharacterData {
    id: string;
    name: string;
    imageSrc: string;
    description: string;
}

interface GameData {
    id: string;
    title: string;
    imageSrc: string;
    date: string;
    description: string;
    categories: string[];
    detail: string;
    downloadLink: string;
    playLink: string;
    longDescription: string;
    privacyPolicyLink: string;
    screenshots: string[];
    characters: string[];
}

export const GamePage = () => {
    const {id} = useParams();
    const game = (games as GameData[]).find((p) => p.id === id);

    if (!game) {
        return <div></div>;
    }

    const filteredCharacters = (characters as CharacterData[]).filter((c) =>
        game.characters.includes(c.id)
    );

    useEffect(() => {
        document.title = `${game.title} | mustakuusi`;
    }, [game.title]);

    return (
        <div>
            <Navbar/>
            <Hero
                title={game.title}
                description={game.description}
                downloadLink={game.downloadLink}
                playLink={game.playLink}
                imageUrl={game.imageSrc}
            />
            <About
                about="Tentang Gim"
                itemDescription={game.longDescription}
                privacyPolicyLink={game.privacyPolicyLink}
            />
            <Characters characterSection="Karakter di Gim" characters={filteredCharacters}/>
            <Screenshots
                screenshots={game.screenshots}
                title={game.title}
            />
            <Contact/>
        </div>
    );
};

// mustakuusi-angular/src/app/pages/game-page/game-page.ts
import {Component, OnInit} from '@angular/core';
import {ActivatedRoute} from '@angular/router';
import {CommonModule} from '@angular/common';
import {Navbar} from '../../components/navbar/navbar';
import {Hero} from '../../components/hero/hero';
import {About} from '../../components/about/about';
import {Characters} from '../../components/characters/characters';
import {Screenshots} from '../../components/screenshots/screenshots';
import {Contact} from '../../components/contact/contact';
import charactersData from '../../../data/characters.json';
import gamesData from '../../../data/games.json';

interface CharacterData {
  id: string;
  name: string;
  imageSrc: string;
}

interface GameData {
  id: string;
  title: string;
  imageSrc: string;
  date: string;
  description: string;
  categories: string[];
  detail: string;
  downloadLink: string;
  playLink: string;
  longDescription: string;
  privacyPolicyLink: string;
  screenshots: string[];
  characters: string[];
}

@Component({
  selector: 'app-game-page',
  standalone: true,
  imports: [
    CommonModule,
    Navbar,
    Hero,
    About,
    Characters,
    Screenshots,
    Contact
  ],
  templateUrl: './game-page.html',
})
export class GamePage implements OnInit {
  game?: GameData;
  filteredCharacters: CharacterData[] = [];

  constructor(private route: ActivatedRoute) {}

  ngOnInit(): void {
    const id = this.route.snapshot.paramMap.get('id');
    const games = gamesData as GameData[];
    const characters = charactersData as CharacterData[];

    this.game = games.find((p) => p.id === id);

    if (this.game) {
      document.title = `${this.game.title} | mustakuusi`;
      this.filteredCharacters = characters.filter((c) =>
        this.game?.characters.includes(c.id)
      );
    }
  }
}
