// mustakuusi-react/src/pages/PrivacyPolicyPage.tsx
import {useParams} from "react-router-dom";
import {useEffect} from "react";
import {Navbar} from "../components/Navbar/Navbar";
import {Privacy} from "../components/Privacy/Privacy";
import {Contact} from "../components/Contact/Contact";
import games from "../../../public/data/games.json";

export const PrivacyPolicyPage = () => {
    const {id} = useParams();
    const game = games.find((p) => p.id === id);

    if (!game) {
        return <div></div>;
    }

    useEffect(() => {
        document.title = `${game.title} | mustakuusi`;
    }, [game.title]);

    return (
        <div>
            <Navbar/>
            <Privacy
                id={id}
                title={game.title}/>
            <Contact/>
        </div>
    );
};

// mustakuusi-angular/src/app/pages/privacy-policy-page/privacy-policy-page.ts
import {Component, OnInit} from '@angular/core';
import {ActivatedRoute} from '@angular/router';
import {CommonModule} from '@angular/common';
import {Navbar} from '../../components/navbar/navbar';
import {Privacy} from '../../components/privacy/privacy';
import {Contact} from '../../components/contact/contact';
import gamesData from '../../../../../public/data/games.json';

interface GameBrief {
  id: string;
  title: string;
}

@Component({
  selector: 'app-privacy-policy-page',
  standalone: true,
  imports: [CommonModule, Navbar, Privacy, Contact],
  templateUrl: './privacy-policy-page.html',
})
export class PrivacyPolicyPage implements OnInit {
  game?: GameBrief;

  constructor(private route: ActivatedRoute) {}

  ngOnInit(): void {
    const id = this.route.snapshot.paramMap.get('id');

    const games = gamesData as GameBrief[];
    this.game = games.find((p) => p.id === id);

    if (this.game) {
      document.title = `${this.game.title} | mustakuusi`;
    }
  }
}
