// mustakuusi-angular/src/app/components/hero/hero.ts
import {Component, Input, OnDestroy, OnInit, signal} from '@angular/core';
import {NavigationEnd, Router} from '@angular/router';
import {CommonModule} from '@angular/common';
import {InViewDirective} from '../../directives/in-view.directive';
import {getImageUrl} from '../../../utils';

@Component({
  selector: 'app-hero',
  standalone: true,
  imports: [CommonModule, InViewDirective],
  templateUrl: './hero.html',
  styleUrl: './hero.css',
})
export class Hero implements OnInit, OnDestroy {
  @Input() title!: string;
  @Input() description?: string;
  @Input() downloadLink?: string;
  @Input() playLink?: string;
  @Input() imageUrl!: string;
  @Input() date?: string;

  isVisible = false;
  currentPath = '';

  isHomePage = false;
  isCharacterPage = false;
  isGamePage = false;

  countdown = signal('');
  private timer: any;

  constructor(private router: Router) {}

  getImageUrl(path: string) {
    return getImageUrl(path);
  }

  getHeroImage() {
    return getImageUrl(this.imageUrl);
  }

  ngOnInit(): void {
    const baseHref = document.querySelector('base')?.getAttribute('href') || '/';

    const path = this.router.url.replace(baseHref, '/').split('#')[0];
    this.currentPath = path;

    this.isHomePage = path === '/';
    this.isCharacterPage = path.startsWith('/character');
    this.isGamePage =
      !this.isHomePage &&
      !this.isCharacterPage &&
      !path.includes('privacy-policy');

    this.router.events.subscribe(event => {
      if (event instanceof NavigationEnd) {
        const pathAfterRedirect = event.urlAfterRedirects.replace(baseHref, '').split('#')[0];
        this.currentPath = pathAfterRedirect;

        this.isHomePage = pathAfterRedirect === '/' || pathAfterRedirect === '';
        this.isCharacterPage = pathAfterRedirect.startsWith('/character');
        this.isGamePage =
          !this.isHomePage &&
          !this.isCharacterPage &&
          !pathAfterRedirect.includes('privacy-policy');
      }
    });

    if (this.date) {
      this.updateCountdown();
      this.timer = setInterval(() => this.updateCountdown(), 1000 * 60 * 60);
    }
  }

  removeHash() {
    setTimeout(() => {
      history.replaceState(null, '', window.location.pathname);
    }, 200);
  }

  updateCountdown() {
    const now = new Date().getTime();
    let release = null;
    if (this.date) {
      release = new Date(this.date).getTime();
    }
    const diff = release ? release - now : 0;

    if (diff <= 0) {
      this.countdown.set('');
      clearInterval(this.timer);
      return;
    }

    const days = Math.floor(diff / (1000 * 60 * 60 * 24));
    this.countdown.set(`${days} hari lagi`);
  }

  ngOnDestroy() {
    clearInterval(this.timer);
  }
}

// mustakuusi-svelte/src/components/Hero/Hero.svelte
<script lang="ts">
    import {activeRoute} from "@roxi/routify";
    import {useInView} from "../../hooks/useInView";
    import styles from "./Hero.module.css";
    import {getImageUrl} from "../../utils";
    import {onDestroy, onMount} from "svelte";

    export let title: string;
    export let description: string | undefined;
    export let downloadLink: string | undefined;
    export let playLink: string | undefined;
    export let imageUrl: string;
    export let date: string | undefined;

    $: currentPath = $activeRoute?.url.split("#")[0];

    const PREFIX = '/y';
    $: normalizedPath = currentPath.startsWith(PREFIX)
        ? currentPath.slice(PREFIX.length) || '/'
        : currentPath;

    $: isHomePage = normalizedPath === "/";
    $: isCharacterPage = normalizedPath.startsWith("/character");
    $: isGamePage = normalizedPath !== "/" && !normalizedPath.includes("privacy-policy") && !normalizedPath.startsWith("/character");

    const {inView, isVisible} = useInView(0.18);

    let countdown: string = "";

    let timer: number;

    const updateCountdown = () => {
        if (!date) return;

        const now = new Date().getTime();
        const release = new Date(date).getTime();
        const diff = release - now;

        if (diff <= 0) {
            countdown = "";
            clearInterval(timer);
            return;
        }

        const days = Math.floor(diff / (1000 * 60 * 60 * 24));
        countdown = `${days} hari lagi`;
    };

    onMount(() => {
        if (date) {
            updateCountdown();
            timer = setInterval(updateCountdown, 1000 * 60 * 60);
        }
    });

    onDestroy(() => {
        clearInterval(timer);
    });
</script>

<section
        use:inView
        class={`${styles.container} ${styles.fadeUp} ${$isVisible ? styles.visible : ""}`}
>
    <div class={styles.content}>
        <h1 class={styles.title}>{title}</h1>
        {#if description}
            <p class={styles.description}>{@html description}</p>
        {/if}

        {#if isHomePage}
            <a href="#games" class={styles.gameBtn} on:click={() => {
                setTimeout(() => {
                    history.replaceState(null, '', window.location.pathname);
                    }, 200);
            }}>Cari Gim</a>
        {/if}

        {#if isGamePage}
            <div class={styles.buttonGroup}>
                {#if countdown}
                    <h2 class={styles.badge}>{countdown}</h2>
                {/if}
                {#if !countdown && downloadLink}
                    <a href={downloadLink} target="_blank" rel="noopener"><img
                            src={getImageUrl("googlebadge.png")}
                            alt="Unduh di Google Play"
                            class={styles.badge}
                    /></a>
                {/if}
                {#if !countdown && playLink}
                    <a href={playLink} target="_blank" rel="noopener"><img
                            src={getImageUrl("itchbadge.png")}
                            alt="Main di itch.io"
                            class={styles.badge}
                    /></a>
                {/if}
            </div>
        {/if}
    </div>

    <img
            src={getImageUrl(imageUrl)}
            alt="hero"
            class={isCharacterPage ? styles.characterHeroImg : styles.heroImg}
    />
</section>
